const CARD_ROTATE_DURATION = 500;
const OPEN_CARD_DURATION = 2500;
const HIDDEN_CLASS = 'hidden';
const HIDE_CARD_DELAY = 1000;

export { CARD_ROTATE_DURATION, OPEN_CARD_DURATION, HIDDEN_CLASS, HIDE_CARD_DELAY };

